### PR TITLE
issue  #257

### PR DESCRIPTION
**Pull request by amanbora**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](../resources/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by wtrocki** [comment]
Looks like it is still failing :(

**Comment by wtrocki** [comment]
@amanbora WDYT about migrating out of the ava to jest. This should be quite quick as amount of tests are very small here

**Comment by amanbora** [comment]
`npm run compile` is working now.
Trying to debug `npm test`

**Comment by amanbora** [comment]
@wtrocki migrating to jest is quite easy, we can try it out for sure.

**Comment by wtrocki** [comment]
Yep.. That will be ultimate fix. We kinda love jest in aerogear and moving away from ava.

**Comment by amanbora** [comment]
@wtrocki ok I'll try to do that?

**Comment by wtrocki** [comment]
Yes. Go for it. CC @darahayes @craicoverflow

**Comment by amanbora** [comment]
@wtrocki all tests are under `examples/tests` right?

**Comment by wtrocki** [comment]
They will be in every package as well

**Comment by amanbora** [comment]
I'm using `npx jest-codemod` to migrate from `ava` to `jest`, but it might face some problems because of some asyn functions.

**Comment by darahayes** [comment]
@amanbora We've since gotten this issue fixed so I'm going to close this PR. If you'd like to work on migrating the tests to Jest, you are still more than welcome to do that. Thanks for looking into this!

**Pull request closed without merging**
