### PR TITLE
AEROGEAR-10108: Remove unused files

### PR DESCRIPTION
**Pull request by joaedwar**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [x] documentation is changed or added
- [ ] commit message follows [commit guidelines](../doc/guides/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by pwright** [comment]
@wtrocki  could you merge this?

**Comment by wtrocki** [comment]
I think that doc/integreatly/modules/ROOT/pages/ds-openshift.adoc is being used

**Comment by darahayes** [comment]
@joaedwar looks like there are conflicts on the `doc/integreatly/modules/ROOT/pages/ds-openshift.adoc` file. Can you rebase your branch please? Also, as @wtrocki pointed out, should it definitely be removed?

**Comment by joaedwar** [comment]
@wtrocki @darahayes .I removed the **mdc client file** that was included in the doc/integreatly/modules/ROOT/pages/ds-openshift.adoc. This PR does not remove the ds-openshift.adoc file. I'll get rid of that change, if it is messing with things.

**Comment by wtrocki** [comment]
I will rebase and merge this changes

**Comment by wtrocki** [comment]
Merged into #216

**Pull request closed without merging**
